#!/usr/bin/env bash

# determines is dirty current working tree or not
function git_dirty() {
    [[ $(git status 2> /dev/null | tail -n1) != "nothing to commit (working directory clean)" ]] && echo "*"
}

# returns current branch if on git repos now
function current_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(git_dirty)/"
}

if tput setaf 1 &> /dev/null; then
    tput sgr0
    if [[ $(tput colors) -ge 256 ]] 2>/dev/null; then
        GREEN=$(tput setaf 119)
        BLUE=$(tput setaf 11)
        MAGENTA=$(tput setaf 93)
    else
        GREEN=$(tput setaf 2)
        BLUE=$(tput setaf 4)
        MAGENTA=$(tput setaf 5)
    fi
    BOLD=$(tput bold)
    RESET=$(tput sgr0)
else
    BLUE="\033[1;34m"
    GREEN="\033[1;32m"
    MAGENTA="\033[1;35m"
    BOLD=""
    RESET="\033[m"
fi

export BLUE
export GREEN
export MAGENTA
export BOLD
export RESET

# update console
export PS1="\[${BOLD}${GREEN}\]\u@\h \[${BLUE}\]\w\$([[ -n \$(git branch 2> /dev/null) ]] && echo \" on \")\[${MAGENTA}\]\$(current_git_branch)\n\[${BLUE}\]$ \[$RESET\]"
