#!/usr/bin/env bash

# completion for dotfiles install script
function __dotfiles_comp() {
    local cur

    COMPREPLY=()
    cur=${COMP_WORDS[COMP_CWORD]}

    case "$cur" in
        *)
            COMPREPLY=( $(compgen -W '-h --help -f --force --prefix=' -- $cur) );;
    esac

    return $SUCCESS
}
complete -F __dotfiles_comp -o filenames install.sh
