#!/usr/bin/env bash

# completion for dotfiles bootstrap
function __bootsrap_comp() {
    local cur

    COMPREPLY=()
    cur=${COMP_WORDS[COMP_CWORD]}

    case "$cur" in
        *)
            COMPREPLY=( $(compgen -W '-h --help -f --force --prefix=' -- $cur) );;
    esac

    return $SUCCESS
}
complete -F __bootsrap_comp -o filenames bootstrap.sh
