#!/usr/bin/env bash
# get git completion work with aliases

__git_complete g __git_main
__git_complete gl _git_pull
__git_complete gp _git_push
__git_complete gb _git_branch
__git_complete ggo _git_branch
__git_complete gco _git_checkout
__git_complete gr _git_remote
__git_complete grs _git_remote
__git_complete gdel _git_branch
__git_complete gss _git_stash
__git_complete gsp _git_stash
__git_complete gri _git_rebase
