#!/usr/bin/env bash

# Usage: dataurl <path>
# create a data url from image or font
[[ $# -eq 1 && -e "$1" ]] || { echo 'Usage: dataurl <path>'; exit; }

ext=${1##*.}
case $ext in
    png|PNG)
        mime='image/png';;
    jpg|jpeg|JPG|JPEG)
        mime='image/jpeg';;
    gif|GIF)
        mime='image/gif';;
    tif|tiff|TIF|TIFF)
        mime='image/tiff';;
    ttf|eot|TTF|EOT)
        mime='font/truetype';;
    otf|OTF)
        mime='font/opentype';;
    woff|WOFF)
        mime='font/woff';;
esac

[[ -z $mime ]] && { echo 'Unknown mime type'; exit; }

echo "data:${mime};base64,`openssl base64 -in "$1"`" | tr -d '\n'
