#!/usr/bin/env bash

# Usage: git-go <name> [<start point>]
# Checkout to branch <name> if exists or create a new one.

# Show inline help if no arguments
if [[ $# -eq 0 ]]; then
    echo 'Usage: git-go <name> [<start point>]'
    exit;
fi

name=$1
exists=`git branch | grep -w $name`

if [[ $exists ]]; then
    git checkout $name
else
    if [ $# -eq 2 ]; then
        git checkout -b $name $2
    else
        git checkout -b $name
    fi
fi
