#!/usr/bin/env bash
#
#: usage: git-go <name>
#:
#: Checkout to branch <name> if exists or create a new one.

function help() {
    sed -En 's/^#:[[:space:]]?//p' $0
}

function slugify() {
    echo "$*" | sed -e 's/ /-/g' | tr '[:upper:]' '[:lower:]'
}

if [[ $# -eq 0 ]]; then
    help && exit;
fi

name="$(slugify $*)"
echo $name | pbcopy
exists=`git branch | grep -w $name`

if [[ $exists ]]; then
    git checkout $name
else
    git checkout -b $name
fi
