#!/usr/bin/env bash

# Usage: push_ssh_cert [-c <certificate>] <host> [<host> ...]
# push SSH public key <certificate> to remote hosts
cert=$(whoami)

[[ "$1" == "-c" && ! -z "$2" ]] && { cert=$2; shift 2; }

test -f ~/.ssh/$cert || ssh-keygen -t dsa -f ~/.ssh/$cert

for host in "$@"; do
    ssh $host 'cat >> ~/.ssh/authorized_keys' < ~/.ssh/$cert.pub
done
