#!/usr/bin/env bash

alias gcl='git clone'
alias ga='git add'
alias gap='git add -p'
alias gaa='git add . -p'
alias gall='git add .'
alias g='git'
alias ggo='git checkout -b'
alias get='git'
alias gst='git status'
alias gs='git status'
alias gsu='git status -s'
alias gl='git pull'
alias gup='git fetch && git rebase'
alias gp='git push'
alias gpo='git push origin'
alias gpa='git push --all'
alias gdv='git diff -w "$@" | vim -R -'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gci='git commit --interactive'
alias gb='git branch'
alias gba='git branch -a'
alias gcount='git shortlog -sn'
alias gcp='git cherry-pick'
alias gco='git checkout'
alias gexport='git archive --format zip --output'
alias gdel='git branch -D'
alias gmu='git fetch origin -v; git fetch upstream -v; git merge upstream/master'
alias gll='git log --graph --pretty=oneline --abbrev-commit'
alias gr='git remote'
alias grs='git remote -v'
alias gss='git stash'
alias gsp='git stash pop'
alias gri='git rebase -i'

case $OSTYPE in
  linux*)
    alias gd='git diff | gvim -R -'
    ;;
  darwin*)
    alias gd='git diff | mate'
    ;;
  darwin*)
    alias gd='git diff'
    ;;
esac
