#!/usr/bin/env bash
# useful system shortcuts

alias ls='ls --color=auto'
# long listing format
alias ll='ls -lh --group-directories-first'
# show hidden files
alias lla='ls -Al'
# show hidden files short
alias la='ls -A'
# sort by size
alias lS='ll -S'
 # sort by extension
alias lx='ls -lhXB'
# sort by date, most recent last
alias lt='ls -lhtr'
alias less='less -m'
# show disk usage in kilo
alias du='du -kh'
# show human-readable information about the file system
alias df='df -h'

# find and remove swap files
alias cleanup.swp="find . -type f -name '*.sw?' -ls -delete"
# remove failed thumbnails
alias cleanup.thumbnails="rm -rf .thumbnails/fail/gnome-thumbnail-factory/*"
# ROT13 encode/decode text
alias rot13='tr a-zA-Z n-za-mN-ZA-M'

# serve files in local dir
alias serve='python -m SimpleHTTPServer'

# reload bash env
alias reload='source ~/.bashrc && echo well done'
