#!/usr/bin/env bash
# useful system shortcuts

alias sl='ls' # common typo
if [[ $OSTYPE == darwin* ]]; then
    alias ls='ls -G'  # color output
    alias ll='ls -lh'
else
    alias ls='ls --color=auto'                  # color output
    alias ll='ls -lh --group-directories-first' # long listing format
fi
alias lla='ls -Al'   # show hidden files
alias la='ls -A'     # show hidden files short
alias lS='ll -S'     # sort by size
alias lx='ls -lhXB'  # sort by extension
alias lt='ls -lhtr'  # sort by date, most recent last
alias less='less -m'
alias du='du -kh'    # show disk usage in kilo
alias df='df -h'     # show human-readable information about the file system

# find and remove swap files
alias cleanup.swp="find . -type f -name '*.sw[op]' -ls -delete"
# remove failed thumbnails
alias cleanup.thumbnails="rm -rf .thumbnails/fail/gnome-thumbnail-factory/*"
# ROT13 encode/decode text
alias rot13='tr a-zA-Z n-za-mN-ZA-M'

alias a=''                     # syntactic sugar
alias an=''                    # syntactic sugar
alias be=''                    # syntactic sugar

alias wat='man'                # show help
alias wat?='!!'                # repeat last command
alias now?='date'              # what time is it?
alias die='sudo kill -9'       # kill by pid
alias pewpewpew='xkill'        # kill what your want
alias ports?='netstat -tulanp' # show opened ports

alias wanna='sudo'                       # run as superuser
alias suod='sudo'                        # common typo
alias dowant='sudo apt-get install'      # install package
alias donotwant='sudo apt-get remove'    # remove package
alias update='sudo apt-get update'       # do update
alias upgrade='sudo apt-get upgrade'     # do upgrade

alias status?='curl -I'                  # fetch the headers from a server
alias serve='python -m SimpleHTTPServer' # serve files in local dir
alias server='serve'                     # same as above

alias reload='source ~/.bashrc && echo Shell environment was reloaded' # reload bash env

alias vi=nvim
alias vim=nvim
