#!/usr/bin/env bash

# useful utils
alias ls='ls --color=auto'
alias ll='ls -lh --group-directories-first'
alias lla='ls -Al'
alias la='ls -A'
alias lS='ll -S'
alias lx='ls -lhXB' # sort by extension
alias lt='ls -lhtr' # sort by date, most recent last
alias less='less -m'
alias du='du -kh'
alias df='df -h'

# find and remove swap files
alias cleanup.swp="find . -type f -name '*.sw?' -ls -delete"
# remove failed thumbnails
alias cleanup.thumbnails="rm -rf .thumbnails/fail/gnome-thumbnail-factory/*"
# ROT13 encode/decode text
alias rot13='tr a-zA-Z n-za-mN-ZA-M'

# serve files in local dir
alias serve='python -m SimpleHTTPServer'
